import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const helperName = "testName";
  return (
    <html lang="en">
      <body className={` bg-primary_white`}>
        <header className="bg-primary_green h-14 flex items-center justify-between p-3 px-16 m-auto">
          <div
            id="logoAndHelperName"
            className="flex items-center gap-4 h-full"
          >
            <a href="#" className="h-full max-w-[70px]">
              <img
                src="./logo_light.png "
                className="h-full object-scale-down"
                alt=""
              />
            </a>
            <div className="w-[2px] h-full bg-[rgb(0_0_0_/_25%)]"></div>
            <h2 className={`primary font-black`}>{helperName}</h2>
          </div>
          <div id="userSide" className="flex items-center">
            {/* clerk avatar goes here  */}
            <a href="#" className="h-full max-w-[30px] block">
              <img src="./history_green.png" className="h-full" alt="" />
            </a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
